SHELL=          /bin/sh
LIBS=           -L/nwprod/lib -lw3_4 -lbufr_s_64 -lbacio_4
FC=             ncepxlf90
FFLAGS=         -qfixed 
LDFLAGS=       -bnoquiet
SRCS=       getnumber.f gtgdef.f igotdata.f inarea.f inlayer.f isitob.f readcntl.f \
            setarea.f setfcst.f setlevel.f setmodel.f setobtyp.f stclst.f stldsp.f \
            stlstr.f stnumb.f stread.f strmbl.f strxbl.f \
            w3fb06.f w3fb11.f w3fb71.f gridtobs.f
OBJS=       getnumber.o gtgdef.o igotdata.o inarea.o inlayer.o isitob.o readcntl.o \
            setarea.o setfcst.o setlevel.o setmodel.o setobtyp.o stclst.o stldsp.o \
            stlstr.o stnumb.o stread.o strmbl.o strxbl.o \
            w3fb06.o w3fb11.o w3fb71.o gridtobs.o
CMD=        verf_gridtobs_gridtobs_ens

all:	$(CMD)

$(CMD):	$(OBJS)
	$(FC) $(FFLAGS)$(LDFLAGS) -g  -o $(@) $(OBJS) $(LIBS)
clean:
	-rm -rf *.o *.lst
