SHELL=          /bin/sh
LIBS=           -L/nwprod/lib -lw3_4 -lbufr_s_64 -lbacio_4
FC=             ncepxlf90
FFLAGS=         -qcheck -qextchk -qfixed 
LDFLAGS=       -bnoquiet
SRCS=       gtgdef.f igotdata.f inarea.f inlayer.f isitob.f readcntl.f \
            setarea.f setfcst.f setlevel.f setmodel.f setobtyp.f stclst.f stldsp.f \
            stlstr.f stnumb.f stread.f streadfho.f streal.f strmbl.f strxbl.f \
            w3fi71.f maskdef.f gridtobs.f
OBJS=       gtgdef.o igotdata.o inarea.o inlayer.o isitob.o readcntl.o \
            setarea.o setfcst.o setlevel.o setmodel.o setobtyp.o stclst.o stldsp.o \
            stlstr.o stnumb.o stread.o streadfho.o streal.o strmbl.o strxbl.o \
            w3fi71.o maskdef.o gridtobs.o
CMD=        verf_gridtobs_gridtobs_fwis

all:	$(CMD)

$(CMD):	$(OBJS)
	$(FC) $(FFLAGS)$(LDFLAGS) -g  -o $(@) $(OBJS) $(LIBS)
clean:
	-rm -rf *.o *.lst
