SHELL=          /bin/sh
LIBS=           -L/nwpara/lib -lw3_4 -lbufr_4_64 -lbacio_4
FC=             ncepxlf90
FFLAGS=         -qcheck -qextchk -qfixed 
LDFLAGS=        -bnoquiet
SRCS=        gtgdef.f  raddate.f  w3fi71.f  editbufr.f
OBJS=        gtgdef.o  raddate.o  w3fi71.o  editbufr.o
CMD=            verf_gridtobs_editbufr

all:	$(CMD)

$(CMD):	$(OBJS)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $(@) $(OBJS) $(LIBS)
clean:
	-rm -rf *.o *.lst
