#!/bin/bash -x
######################################################################
#                                                                    #
#     Makeit script for build of all directories.                    #
#                                                                    #
######################################################################

export JHOME=`pwd`

set +x

##############################
#    Load the modules        #
##############################

source /lfs/h2/emc/vpppg/noscrub/Perry.Shafran/verf_grid2obs/versions/build.ver

module purge

module load envvar/${envvar_ver}
module load intel/${intel_ver}
module load PrgEnv-intel/${PrgEnvintel_ver}
module load craype/${craype_ver}
module load cray-mpich/${craympich_ver}
module load w3emc/${w3emc_ver}
module load w3nco/${w3nco_ver}
module load bufr/${bufr_ver}
module load bacio/${bacio_ver}
module load jasper/${jasper_ver}
module load libjpeg/${libjpeg_ver}
module load libpng/${libpng_ver}
module load zlib/${zlib_ver}
module load g2/${g2_ver}


##############################
#    Converson table         #
##############################
#-----just for reference 
#$(G2_LIB4)        -lg2_4 
#$(W3NCO_LIB4)     -lw3nco_4
#$(W3EMC_LIB4)     -lw3emc_4
#$(BUFR_LIBs)      -lbufr_s_64
#$(BACIO_LIB4)     -lbacio_4
#$(JASPER_LIB)     -ljasper
#$(PNG_LIB)        -lpng
#$(Z_LIB)          -lz

##############################
#    Build the sources       #
##############################
#-----loop over *.fd directories - as of know they are:
#verf_gridtobs_avegrib_pm.fd #verf_gridtobs_editbufr_pmave.fd #verf_gridtobs_gridtobs_ens.fd #verf_gridtobs_gridtobs_pm.fd #verf_gridtobs_prepfits.fd
#verf_gridtobs_editbufr.fd #verf_gridtobs_editbufr_pm.fd #verf_gridtobs_gridtobs.fd #verf_gridtobs_maxgrib_ozone.fd  #verf_gridtobs_prepfits_ozone.fd
#verf_gridtobs_editbufr_ozone.fd #verf_gridtobs_editbufr_pmmax.fd #verf_gridtobs_gridtobs_fwis.fd #verf_gridtobs_maxgrib_pm.fd #verf_gridtobs_prepfits_pm.fd
#verf_gridtobs_editbufr_ozonemax.fd #verf_gridtobs_gridtobs_aod.fd #verf_gridtobs_gridtobs_ozone.fd #verf_gridtobs_prepfits_aod.fd #verf_gridtobs_writemask.fd

for dir in $( ls -d *.fd ); do

echo "                                                          "
echo "                                                          "
echo "=========================================================="
echo "========compiling $dir=========="
echo "=========================================================="

cd $JHOME/$dir

make -f makefile clean
make -f makefile

done

exit
