#!/bin/bash -x
######################################################################
#                                                                    #
#     Makeit script for build of all directories.                    #
#                                                                    #
######################################################################

export JHOME=`pwd`

set +x

##############################
#    Load the modules        #
##############################
module purge
module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load intel
module load craype/2.7.8
module load cray-mpich/8.1.7
module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/19.1.3.304
module load hpc-cray-mpich/8.1.7

module load g2/3.4.3
#module load w3nco/2.4.1
module load w3emc/2.9.0
module load bufr/11.5.0
module load bacio/2.4.1
module load jasper/2.0.25
module load jpeg/9.1.0
module load png/1.6.35
module load zlib/1.2.11

#module load w3nco/2.4.1 
#module load w3emc/2.9.0
##module load /lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7/w3emc/2.7.3.lua
#module load bacio/2.4.1
#module load bufr/11.5.0
#module load g2/3.4.3
#module load zlib/1.2.11
#module load png/1.6.35
#module load jpeg/9.1.0
#module load jasper/2.0.25
module list


##############################
#    Converson table         #
##############################
#-----just for reference 
$(G2_LIB4)        -lg2_4 
$(W3NCO_LIB4)     -lw3nco_4
$(W3EMC_LIB4)     -lw3emc_4
$(BUFR_LIBs)      -lbufr_s_64
$(BACIO_LIB4)     -lbacio_4
$(JASPER_LIB)     -ljasper
$(PNG_LIB)        -lpng
$(Z_LIB)          -lz

##############################
#    Build the sources       #
##############################
#-----loop over *.fd directories - as of know they are:
#verf_gridtobs_avegrib_pm.fd #verf_gridtobs_editbufr_pmave.fd #verf_gridtobs_gridtobs_ens.fd #verf_gridtobs_gridtobs_pm.fd #verf_gridtobs_prepfits.fd
#verf_gridtobs_editbufr.fd #verf_gridtobs_editbufr_pm.fd #verf_gridtobs_gridtobs.fd #verf_gridtobs_maxgrib_ozone.fd  #verf_gridtobs_prepfits_ozone.fd
#verf_gridtobs_editbufr_ozone.fd #verf_gridtobs_editbufr_pmmax.fd #verf_gridtobs_gridtobs_fwis.fd #verf_gridtobs_maxgrib_pm.fd #verf_gridtobs_prepfits_pm.fd
#verf_gridtobs_editbufr_ozonemax.fd #verf_gridtobs_gridtobs_aod.fd #verf_gridtobs_gridtobs_ozone.fd #verf_gridtobs_prepfits_aod.fd #verf_gridtobs_writemask.fd

for dir in $( ls -d *.fd ); do

echo "                                                          "
echo "                                                          "
echo "=========================================================="
echo "========compiling $dir=========="
echo "=========================================================="

cd $JHOME/$dir

make -f makefile clean
make -f makefile

done

exit
