#!/bin/bash

##############################
#    Load modules            #
##############################
module purge
module use /gpfs/dell1/nco/ops/nwprod/modulefiles
module load EnvVars/1.0.2
module load ips/18.0.1.163 
module load impi/18.0.1
module load ip/3.0.1
module load g2/3.1.0
module load impi/18.0.1
module load w3nco/2.0.6 
module load crtm/2.2.5
module load rsync/3.1.2
module load zlib/1.2.11
module load NetCDF/4.5.0
module load bacio/2.0.2
module load nemsio/2.2.3
module load pm5/1.0
module load prod_envir/1.0.2
module load cmake/3.10.0
module load sfcio/1.0.0
module load w3emc/2.3.0
module load subversion/1.7.16
module load grib_util/1.1.0
module load bufr/11.3.0
module load HPSS/5.0.2.5
module load prod_util/1.1.0
module load jasper/1.900.1
module load sp/2.0.2
module load sigio/2.0.1
module load mktgs/1.0 
module load libpng/1.2.59
module load CFP/2.0.2
module load bufr_dumplist/2.0.2
module load dumpjb/5.1.0

#module load ruby/2.5.1        
#module load git/2.14.3
#module load rocoto/1.2.4
#module load GrADS/2.2.0
module list

exit

