#!/bin/sh

OBJS    = gtgdef.o raddate.o w3fi63.o w3fi71.o editbufr.o
LIBS	=  -lw3emc_4 -lw3nco_4 -lbufr_4_64 -lbacio_4
FC 	= ifort
FFLAGS 	= -heap-arrays 
CMD     = verf_gridtobs_editbufr_ozone

$(CMD):	$(OBJS)
	$(FC) $(FFLAGS) -o $(@) $(OBJS) $(LIBS) 
clean:
	rm -f *.o $(CMD)
