SHELL=          /bin/sh
LIBS=           -L/home/George.Vandenberghe/nwprod/libintel -lw3-2.0_4 -lbufr_s_64 -lbacio_4
FC=             ifort
FFLAGS=         -heap-arrays
LDFLAGS=        
SRCS=        gtgdef.f  raddate.f  w3fi71.f  editbufr.f
OBJS=        gtgdef.o  raddate.o  w3fi71.o  editbufr.o
CMD=            verf_gridtobs_editbufr

all:	$(CMD)

$(CMD):	$(OBJS)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $(@) $(OBJS) $(LIBS)
clean:
	-rm -rf *.o *.lst
